application: rssnotifierapp
version: zack
runtime: python
api_version: 1

handlers:

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.(gif|png|jpg|txt|ico))
  static_files: static/\1
  upload: static/(.*)

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: rssnotifier.py

builtins:
- appstats: on

inbound_services:
- xmpp_presence
